Add support for Firebase, basic auth actions, rough draft for core data types
asbhaskar/shareable-frontend pull request #1
Opened 2023-01-30 05:15 UTC by scott-t-robinson

- Firebase support https://console.firebase.google.com/u/0/project/shareable-mvp/overview
- General functions for authentication through google/other email
- Rough draft for core data types user, organization, groups, requests, insights
- Skeleton for adding requests/insights to Firestore database, collections schema subject to change

2023-02-04 21:46 UTC, asbhaskar requested changes
Good start, just a few comments/questions below.

2023-02-04 21:46 UTC, asbhaskar commented on src/types/filedRequest.ts
> +}
Could we replace enunms with types? e.g. ``` type RequestPriority = 'Low' | 'Medium' | 'High'  ```

2023-02-04 21:46 UTC, asbhaskar commented on src/types/filedRequest.ts
> +    createDate: number;
Can we move interfaces into ```src/interfaces/```

2023-02-04 21:46 UTC, asbhaskar commented on public/index.html
> +<!DOCTYPE html>
I don't think we need this file it looks like it's for vanillaJS apps. You also haven't included a reference for vite to use this file

2023-02-04 21:46 UTC, asbhaskar commented on src/actions/userAuthActions.ts
> +           setDoc(doc(firestore, "users", userCredential.user.uid), {
Please destructure userCredentials here like ``` const {email, password, user: {uid}} = useCredentials ```

2023-02-04 21:46 UTC, asbhaskar commented on .firebaserc
> +}
We have this information in the src/firebase.ts file, is this one necessary?

2023-02-04 21:46 UTC, asbhaskar commented on .firebaserc
> +}
Do we need this? The information is also in ```src/firebase.ts```

2023-02-04 21:46 UTC, asbhaskar commented on firebase.json
> +    ],
We are not hosting the application on firebase, I don't think we need this file

2023-02-04 21:46 UTC, asbhaskar commented on package.json
> +    "firebase-tools": "^11.21.0",
I'm not sure if firebase-tools is necessary, I don't think we need to access the CLI from the frontend

2023-02-04 21:46 UTC, asbhaskar commented on src/types/filedRequest.ts
> +}
Technically I think you can do this directly in interfaces now but I think it helps with organization

2023-02-04 21:53 UTC, asbhaskar commented on src/actions/userAuthActions.ts
> +export const signUp = (userCredentials: any) => {
Please defined types for userCredentials, maybe ```{email: string, password: string, user: {id: number}}``` or something based on what you have below

2023-02-12 23:41 UTC, scott-t-robinson commented
Pretty sure all comments are addressed. Im scared of the Vercel failure, may be because public/index.html was removed. I get a 404 when checking on Vercel, could you add me

2023-02-12 23:43 UTC, asbhaskar commented
@scott-t-robinson I'll get back to you with the code review later, here's the vercel error:
<img width="1236" alt="Screen Shot 2023-02-12 at 3 42 25 PM" src="https://user-images.githubusercontent.com/18740303/218344335-95567517-81eb-41aa-9d37-f61568e20cd8.png">

Unsure if we have to pay to add people to vercel but ill look that up later as well.

2023-02-13 00:00 UTC, scott-t-robinson commented
Thanks, fixed that build error

2023-02-13 01:19 UTC, asbhaskar approved these changes
LGTM, I'll hook the sign in apis up and test it sometime this week

2023-02-22 23:43 UTC, merged